export const SIGNIN_INPUTS = "SIGNIN_INPUTS";

export const ADD_USER = "ADD_USER";

export const LOGIN_INPUTS = "LOGIN_INPUTS";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const FETCH_THEATRES = "FETCH_THEATRES";

export const SELECT_SEATS = "SELECT_SEATS";

export const RESERVED_SEATS = "RESERVED_SEATS";

export const ADDMOVIES_INPUTS = "ADDMOVIES_INPUTS";

export const ADD_MOVIES = "ADD_MOVIES";

export const FETCH_MOVIES = "FETCH_MOVIES";
